### ISSUE TITLE
New Firefox update disables the add-on

### ISSUE THREAD

**Issue by nmzaheer** [studentenraad/kotnetlogin-extension#8]
Error message says that add-on needs to be signed and due to security reasons unsigned addons are disabled

Firefox version : 43.0.1
Operating System : Windows 10

**Comment by vierbergenlars** [comment]
I just got a version signed by mozilla, can you try if it works for you?
You can download it at https://vbgn.be/s2C

**Comment by nmzaheer** [comment]
Checked it out. Installs cleanly and no warnings/disable now. Tested with Toledo and it works. Thanks for the update.

**Comment by GijsTimmers** [comment]
Could you put the xpi file in the releases section?

**Comment by nmzaheer** [comment]
@GijsTimmers I think the xpi file is already included in the releases section. Did you try it out?

**Comment by GijsTimmers** [comment]
@nmzaheer Apparently it is. Didn't look close enough. Thank you.

The normal kotnetlogin.xpi is still in there which is a bit strange though, as it doesn't work.

**Comment by vierbergenlars** [comment]
Strange, I thought I deleted the unsigned version.

It is deleted now anyhow.
