### ISSUE TITLE
Toledo update and kotnetlogin-extension

### ISSUE THREAD

**Issue by Junevanaalst** [studentenraad/kotnetlogin-extension#9]
KULeuven Toledo has updated and has a new interface. But when you use the kotnetlogin-extension you automatically sign in on the old toledo page in stead of the new. Only when you disable the kotnetlogin-extension you can access the new toledo.
How can this be solved?

**Comment by vierbergenlars** [comment]
There is a new version of the plugin available that will log in to the new version of toledo.
https://github.com/studentenraad/kotnetlogin-extension/releases/tag/2.0.7

The firefox version should update automatically, but the chrome version has to be reinstalled manually
